name: tripso
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
<<<<<<< HEAD
  google_fonts: ^4.0.4
=======
  google_fonts: ^6.1.0
>>>>>>> 9ba9d52b02061d4766995a2ed3e1898c0bede29d
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  hexcolor: ^3.0.1
  bot_toast: ^4.0.3
  fluttertoast: ^8.1.2
  flutter_iconly: ^1.0.2
<<<<<<< HEAD
  intl: ^0.18.1
  conditional_builder_null_safety: ^0.0.6
  carousel_slider: ^4.1.1
  flutter_launcher_icons: ^0.13.1
  timeago: ^3.3.0
  rflutter_alert: ^2.0.4
  responsive_framework: ^1.1.0
  simple_animations: ^4.2.0
=======
  intl: ^0.19.0
  conditional_builder_null_safety: ^0.0.6
  carousel_slider: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  timeago: ^3.3.0
  rflutter_alert: ^2.0.4
  responsive_framework: ^1.1.1
  simple_animations: ^5.0.2
>>>>>>> 9ba9d52b02061d4766995a2ed3e1898c0bede29d
  supercharged: ^2.1.1
  google_nav_bar: ^5.0.6
  http: ^1.1.0
  provider: ^6.0.5
  url_launcher: ^6.1.7
  cached_network_image: ^3.2.3
<<<<<<< HEAD
  image_picker: ^0.8.6+1
  image_cropper: ^4.0.1
=======
  image_picker: ^1.0.4
  image_cropper: ^8.0.2
>>>>>>> 9ba9d52b02061d4766995a2ed3e1898c0bede29d
  animated_splash_screen: ^1.3.0
  font_awesome_flutter: ^10.4.0
  smooth_page_indicator: ^1.1.0


  # firebase
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  firebase_storage: ^12.3.1
  flutter_tts: ^4.0.2
  flutter_screenutil: ^5.6.1
  wakelock: ^0.6.2
  internet_connection_checker: ^1.0.0+1
<<<<<<< HEAD
  connectivity_plus: ^4.0.1
=======
  connectivity_plus: ^6.0.5
>>>>>>> 9ba9d52b02061d4766995a2ed3e1898c0bede29d
  flutter_svg: ^2.0.5
  page_transition: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/images/ancient/

