name: tripso
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  google_fonts: ^4.0.4
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  hexcolor: ^3.0.1
  bot_toast: ^4.0.3
  fluttertoast: ^8.1.2
  flutter_iconly: ^1.0.2
  intl: ^0.18.1
  conditional_builder_null_safety: ^0.0.6
  carousel_slider: ^4.1.1
  flutter_launcher_icons: ^0.13.1
  timeago: ^3.3.0
  rflutter_alert: ^2.0.4
  responsive_framework: ^1.1.0
  simple_animations: ^4.2.0
  supercharged: ^2.1.1
  google_nav_bar: ^5.0.6
  http: ^0.13.5
  provider: ^6.0.5
  url_launcher: ^6.1.7
  cached_network_image: ^3.2.3
  image_picker: ^0.8.6+1
  image_cropper: ^4.0.1
  animated_splash_screen: ^1.3.0
  font_awesome_flutter: ^10.4.0
  smooth_page_indicator: ^1.1.0


  # firebase
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  cloud_firestore: ^4.0.3
  firebase_storage: ^11.0.3
  flutter_tts: ^3.6.2
  flutter_screenutil: ^5.6.1
  wakelock: ^0.6.2
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^4.0.1
  flutter_svg: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^2.0.1

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/images/ancient/

