name: tripso
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ^3.5.4

dependencies:
  animated_splash_screen: ^1.3.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.5.0
  connectivity_plus: ^6.1.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.6
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_iconly: ^1.0.2
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.15
  flutter_tts: ^4.2.0
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.7
  http: ^1.2.2
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  page_transition: ^2.1.0
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/ancient/
