name: tripso
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  google_fonts: ^3.0.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  hexcolor: ^3.0.1
  bot_toast: ^4.0.3
  fluttertoast: ^8.1.1
  flutter_iconly: ^1.0.2
  intl: ^0.17.0
  conditional_builder_null_safety: ^0.0.6
  carousel_slider: ^4.1.1
  flutter_launcher_icons: ^0.10.0
  timeago: ^3.3.0
  rflutter_alert: ^2.0.4
  responsive_framework: ^0.2.0
  simple_animations: ^4.2.0
  supercharged: ^2.1.1
  email_auth: ^1.0.0
  pin_code_fields: ^7.4.0
  lottie: ^2.0.0
  google_nav_bar: ^5.0.6
  http: ^0.13.5
  provider: ^6.0.5
  auto_size_text: ^3.0.0
  url_launcher: ^6.1.7




  # firebase
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  cloud_firestore: ^4.0.3
  firebase_storage: ^11.0.3
  firebase_messaging: ^14.0.3
  flutter_tts: ^3.6.2
  flutter_screenutil: ^5.6.1
  wakelock: ^0.6.2
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^3.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/images/2.0x/
    - assets/images/3.0x/