name: tripso
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  bloc: ^8.1.0
  cached_network_image: ^3.2.3
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.4.2
  conditional_builder_null_safety: ^0.0.6
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  firebase_storage: ^12.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_iconly: ^1.0.2
  flutter_screenutil: ^5.6.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.5
  flutter_tts: ^4.0.2
  fluttertoast: ^8.1.2
  font_awesome_flutter: ^10.4.0
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  http: ^1.1.0
  image_cropper: ^8.0.2
  image_picker: ^1.0.4
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  page_transition: ^2.1.0
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/ancient/
