// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1-5oxUzhGHEocdJny8ZF5sIfl1tLt4Ws',
    appId: '1:536479207520:web:f67e9942c8411514f0b305',
    messagingSenderId: '536479207520',
    projectId: 'tripso-ac883',
    authDomain: 'tripso-ac883.firebaseapp.com',
    storageBucket: 'tripso-ac883.appspot.com',
    measurementId: 'G-6QBKKYNX5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwTFt1yGvqAv-7pm6q8SyY0bCyiQQaB_A',
    appId: '1:536479207520:android:3c6ddd2ef8fe2ba2f0b305',
    messagingSenderId: '536479207520',
    projectId: 'tripso-ac883',
    storageBucket: 'tripso-ac883.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy099suu_7NhRApL9iD5BVjseZHVxJyJo',
    appId: '1:536479207520:ios:52150d462528a67df0b305',
    messagingSenderId: '536479207520',
    projectId: 'tripso-ac883',
    storageBucket: 'tripso-ac883.appspot.com',
    iosClientId: '536479207520-atp51lgm4hpnfcp2b4ce1gd28rpq5gfp.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripso',
  );

}